# Generated by Django 4.0.1 on 2022-01-14 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(help_text='Please add a user name less than 100 characters long', max_length=100, unique=True)),
                ('password', models.CharField(help_text='Please add a password less than 50 characters long', max_length=50)),
                ('first_name', models.CharField(blank=True, default='Guest', max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('height', models.PositiveIntegerField()),
                ('width', models.PositiveIntegerField()),
                ('color', models.CharField(choices=[('RED', 'Red'), ('BLU', 'Blue'), ('GRN', 'Green'), ('WHT', 'White'), ('BLK', 'Black')], max_length=3)),
                ('image', models.ImageField(height_field='height', help_text='Please add a image', upload_to='images', width_field='width')),
                ('permission', models.SmallIntegerField(choices=[(0, 'Private'), (1, 'Public')], default=0)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_repository.user')),
            ],
        ),
    ]
