# Generated by Django 4.0.1 on 2022-01-15 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_repository', '0002_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(height_field='height', help_text='Please add a image', upload_to='images/', width_field='width'),
        ),
    ]
